# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: SSH@0
  inputs:
    sshEndpoint: 'l4d2.gazo.win'
    runOptions: 'commands'
    commands: |
      cp -R $(Build.Repository.LocalPath)/* /home/ubuntu/bcard-ui.tuldok.dev
      touch /home/ubuntu/bcard-ui.tuldok.dev/restarter.file